// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH6GXml1ba4rYGRAeTEvqvmALEH1IKim8',
    appId: '1:528893558394:web:f860cda372f077259485c3',
    messagingSenderId: '528893558394',
    projectId: 'vocallabs-fc7d5',
    authDomain: 'vocallabs-fc7d5.firebaseapp.com',
    storageBucket: 'vocallabs-fc7d5.firebasestorage.app',
    measurementId: 'G-14TKNE3RKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHpz7LYRjUWQuPT1Fds1zWPchtDOE79c',
    appId: '1:528893558394:android:0f43ce1c669baa189485c3',
    messagingSenderId: '528893558394',
    projectId: 'vocallabs-fc7d5',
    storageBucket: 'vocallabs-fc7d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXGLxtSWwPu4TRqBUrb3edU_J6EouwJg',
    appId: '1:528893558394:ios:40510023632bfc6a9485c3',
    messagingSenderId: '528893558394',
    projectId: 'vocallabs-fc7d5',
    storageBucket: 'vocallabs-fc7d5.firebasestorage.app',
    iosBundleId: 'com.example.vocallabsFlutterApp',
  );

}